export type NetworkStatus = 'online' | 'offline' | 'syncing' | 'sync-error'
export type PrinterStatus =
  | 'unknown'
  | 'unavailable'
  | 'permission-required'
  | 'ready'
  | 'printing'
  | 'disconnected'
  | 'paper-out'
  | 'cover-open'
  | 'status-unavailable'
  | 'error'
